version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock