version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
